// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbgvfzuubejhlbkxdksc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZ3ZmenV1YmVqaGxia3hka3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTg4NjUsImV4cCI6MjA2MTk3NDg2NX0.Kzd6oKFEPF6dl9Q9laOv2hXs3L8QIoEc-BH0suHHgdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);